### ISSUE TITLE
大佬能给一个编译frpc的文档吗

### ISSUE THREAD

**Issue by huoyanyanyi1** [AceDroidX/frp-Android#13]
我是根据https://github.com/FrpcCluster/frpc-Android/blob/master/Compile_zh.md这个进行编译
编译出的是frpclib.aar  frpclib-sources.jar   不知道怎么加到项目中

**Comment by AceDroidX** [comment]
不用编译 直接复制 参见 #2

**Comment by huoyanyanyi1** [comment]
可以了   谢谢
