### ISSUE TITLE
感谢大佬付出，求一个编译前的源码

### ISSUE THREAD

**Issue by startui** [AceDroidX/frp-Android#19]
rt，想自己编译打包最新版本的frpc二进制文件，感谢大佬

**Comment by AceDroidX** [comment]
我这的libfrpc.so是直接从原项目复制过来的 参见： #2

**Comment by startui** [comment]
> 我这的libfrpc.so是直接从原项目复制过来的 参见： #2

感谢感谢，直接把官方编译好的重命名复制进去就行了，我还以为要把frpc编译成so文件呢
