### ISSUE TITLE
请教libfrpc.so是怎么编译的

### ISSUE THREAD

**Issue by loongwind** [AceDroidX/frp-Android#2]
如题，请教一下你项目中用到的[libfrpc.so](https://github.com/AceDroidX/frp-Android/blob/master/app/src/main/jniLibs/x86_64/libfrpc.so)是怎么编译出来的，谢谢！

**Comment by AceDroidX** [comment]
从源码编译有点麻烦，我还没研究过Android NDK，所以libfrpc.so是直接从[frp的release](https://github.com/fatedier/frp/releases)里复制过来的（

**Comment by loongwind** [comment]
没看到release里有.so文件，是从release的某个包里解压出来的么 @AceDroidX

**Comment by AceDroidX** [comment]
单纯就是把对应ABI的压缩包解压之后重命名frpc为libfrpc.so

**Comment by loongwind** [comment]
看了一下你的代码，明白了，你不是在代码里调用so中的方法，而是把so作为一个可执行文件，然后通过shell去执行对应的命令

**Comment by AceDroidX** [comment]
对的

**Comment by lingchenma** [comment]
frpc 源码编译 链接， https://jinjian.lv/archives/frp.html#comment-8

**Comment by lingchenma** [comment]
目前官方里面有android 版本的，下载安卓版本直接改成 libfrpc.so 替换进去就能直接在安卓下运行了

**Comment by lingchenma** [comment]
> > 目前官方里面有android 版本的，下载安卓版本直接改成 libfrpc.so 替换进去就能直接在安卓下运行了
> 
> 直接下载这个文件,
> 
> <img alt="Image" width="302" height="57" src="https://private-user-images.githubusercontent.com/16060581/462801052-355c345e-5d3d-4f4b-884e-c32db7e94529.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTE3MzY5NzQsIm5iZiI6MTc1MTczNjY3NCwicGF0aCI6Ii8xNjA2MDU4MS80NjI4MDEwNTItMzU1YzM0NWUtNWQzZC00ZjRiLTg4NGUtYzMyZGI3ZTk0NTI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA3MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNzA1VDE3MzExNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxMzMzMDk4MDcyYzhkOTg1MDgzMDkxYzk4ZWRiNTFmZDdlNTM4NjY1MWQxMjgzZDM0NTAwMzkzM2UwNDYzMTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.r4nOfviNMwgaUwm9QzDez5qyqKde8q4Brdd_Lnba4yY"> 命名成 libfrpc.so吗

解压，把里面的文件重命名 libfrpc.so

**Comment by artillerymans** [comment]
<img width="598" height="183" alt="Image" src="https://github.com/user-attachments/assets/01103343-a095-4936-a48e-b28e4024db5c" />
红圈中的两个命名成so? 请教一下 frpc.toml 和 frps.toml 有什么区别?做什么用的针对的是什么场景

**Comment by lingchenma** [comment]
一个是服务器的配置，一个是客户端的配置

**Comment by artillerymans** [comment]
好的 感谢

**Comment by artillerymans** [comment]
> 一个是服务器的配置，一个是客户端的配置

armeabi-v7a  还有 x86_64 你这个两个又是解压哪里的

**Comment by lingchenma** [comment]
armeabi-v7a 是安卓arm32位的，x86_64 是电脑x86模拟器要用的so，
frpc.toml 和 frps.toml  是配置文件
 把 frpc 改名成 libfrpc.so  放到  armeabi-v7a 里面就好了

**Comment by AceDroidX** [comment]
@artillerymans 我问下你有什么需求要换成 android 版本的 frp 内核，如果是dns解析有问题配置里加上 dnsServer 有用吗

顺便解释下我不用 android 版本内核的原因：官方的 release 里只有 arm64 架构的文件，arm32 / x64 的就得自己编译，为了统一运行特性就选择用 linux 版本的了。等我以后有空再考虑重构，直接从 frp 源码编译，不用再手动复制，让构建流程更透明点

**Comment by lingchenma** [comment]
<img width="1187" height="1161" alt="Image" src="https://github.com/user-attachments/assets/da068da4-fbca-46b1-b647-82e946c3b2cd" />

**Comment by maxplustools** [comment]
我看到个编译成aar的项目 并且支持多内核的
https://github.com/jahen/frp
https://github.com/jahen/frp-android
