### ISSUE TITLE
DNS好像有问题

### ISSUE THREAD

**Issue by samuncleorange** [AceDroidX/frp-Android#20]
frpc.toml我填服务器域名，失败。
但是填服务器ip，成功。
（在Win上填域名，同样的网络环境是正常的。）

**Comment by samuncleorange** [comment]
没有。我试试。感谢大佬解答。打扰了。

**Comment by samuncleorange** [comment]
加了一行。dns_server = "114.114.114.114"
报错：unknown field "dns_server"
请问怎么加啊

**Comment by AceDroidX** [comment]
写成`dnsServer = "114.114.114.114"`

**Comment by samuncleorange** [comment]
🌹
