### ISSUE TITLE
1.0.4版本显示错位，1.0.2版本没问题

### ISSUE THREAD

**Issue by jason1235** [AceDroidX/frp-Android#25]
手机型号小米14pro 系统版本安卓15

![微信图片_20241229122900](https://github.com/user-attachments/assets/60ab034a-9e01-4310-ad4e-7c6bd6322867)

**Comment by AceDroidX** [comment]
这个UI库有点老了 下个版本直接上 Material Design 3 + Jetpack Compose

**Comment by AceDroidX** [comment]
更新了 再试试

**Comment by jason1235** [comment]
> 更新了 再试试

谢谢大佬，完美使用，新年快乐～
